### ISSUE TITLE
Rag with local llm

### ISSUE THREAD

**Issue by sojudu** [shubham0204/shubham0204#2]
Kindly bake in a tiny llm into the app and give us the function of rag, so that we can chat with our pdfs, rather than rely on gemini api, kindly also refer mobillama []()https://github.com/mbzuai-oryx/MobiLlama/blob/main/README.md

**Comment by shubham0204** [comment]
Hi @sojudu, I'll be soon integrating a local LLM in the app within the next two weeks
If needed, you can open this issue on the project's repo: https://github.com/shubham0204/Android-Document-QA
I'll update you once the integration has been completed

**Comment by shubham0204** [comment]
The issue was migrated to the project repo: https://github.com/shubham0204/Android-Document-QA/issues/3
